apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-app
  template:
    metadata:
      labels:
        app: lms-app
    spec:
      containers:
      - name: lmspgdb
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "password"
        imagePullPolicy: Always
 

