apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-app
  template:
    metadata:
      labels:
        app: lms-app
    spec:
      containers:
      - name: lms-be
        image: akulakumar333/lmsbe
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@lmspgdb:5432/postgres"
        - name: PORT
          value: "8080"
        - name: MODE
          value: "local"
        imagePullPolicy: Always

