---
apiVersion: v1
kind: Service
metadata:
  name: lmspgdb-service
spec:
  selector:
    app: lms-app
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: lms-be-service
spec:
  selector:
    app: lms-app
  ports:
  - name: lms-be-port
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: lms-fe-service
spec:
  selector:
    app: lms-app
  ports:
  - name: lms-fe-port
    port: 80
    targetPort: 80
  type: LoadBalancer

