apiVersion: v1
kind: Service
metadata:
  name: lms-fe
spec:
  selector:
    app: lms-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: backend
    port: 8080
    targetPort: 8080
  - name: database
    port: 5432
    targetPort: 5432
  type: LoadBalancer

