apiVersion: v1
kind: Service
metadata:
  name: lms-fe
  labels:
    app: lms-app
spec:
  selector:
    app: lms-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer
